version: '3.8'

services:
  lumberjack:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      # Mount uploads directory for persistence
      - ./uploads:/app/server/uploads
      # Mount demo files
      - ../../demo-files:/app/demo-files:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Mount SSL certificates if you have them
    depends_on:
      - lumberjack
    restart: unless-stopped
    profiles:
      - production  # Only start with --profile production
